-- Inserare profesori
INSERT INTO profesor VALUES (1, 'Popescu Ion', 'Prof. Dr.', 'Informatică');
INSERT INTO profesor VALUES (2, 'Ionescu Ana', 'Conf. Dr.', 'Economie');
INSERT INTO profesor VALUES (3, 'Dumitru George', 'Prof. Dr.', 'Limbi Străine');
INSERT INTO profesor VALUES (4, 'Constantin Maria', 'Lector Dr.', 'Drept');
INSERT INTO profesor VALUES (5, 'Vasilescu Andrei', 'Prof. Dr.', 'Medicină');
INSERT INTO profesor VALUES (6, 'Radu Elena', 'Conf. Dr.', 'Științe Politice');
INSERT INTO profesor VALUES (7, 'Popa Liviu', 'Prof. Dr.', 'Inginerie Electrică');
INSERT INTO profesor VALUES (8, 'Ilie Maria', 'Lector Dr.', 'Psihologie');
INSERT INTO profesor VALUES (9, 'Gheorghe Alex', 'Prof. Dr.', 'Arte Vizuale');
INSERT INTO profesor VALUES (10, 'Andrei Carmen', 'Conf. Dr.', 'Sociologie');
INSERT INTO profesor VALUES (11, 'Stancu Radu', 'Prof. Dr.', 'Muzică');
INSERT INTO profesor VALUES (12, 'Popescu Ana', 'Lector Dr.', 'Matematică');
INSERT INTO profesor VALUES (13, 'Gheorghiu Florin', 'Prof. Dr.', 'Agricultură');
INSERT INTO profesor VALUES (14, 'Ionescu Bogdan', 'Conf. Dr.', 'Științe Aplicate');
INSERT INTO profesor VALUES (15, 'Popovici Ionel', 'Prof. Dr.', 'Educație Fizică');
INSERT INTO profesor VALUES (16, 'Dima Gabriela', 'Lector Dr.', 'Chimie');
INSERT INTO profesor VALUES (17, 'Stoica Adrian', 'Prof. Dr.', 'Filosofie');
INSERT INTO profesor VALUES (18, 'Constantinescu Maria', 'Conf. Dr.', 'Geografie');
INSERT INTO profesor VALUES (19, 'Popa Gabriel', 'Prof. Dr.', 'Biologie');
INSERT INTO profesor VALUES (20, 'Dobre Elena', 'Lector Dr.', 'Istorie');
INSERT INTO profesor VALUES (21, 'Vasilescu Tudor', 'Prof. Dr.', 'Drept Penal');
INSERT INTO profesor VALUES (22, 'Gavrilescu Ion', 'Conf. Dr.', 'Informatică Aplicată');
INSERT INTO profesor VALUES (23, 'Nistor Elena', 'Prof. Dr.', 'Arhitectură');
INSERT INTO profesor VALUES (24, 'Stan Ioana', 'Lector Dr.', 'Electronică');
INSERT INTO profesor VALUES (25, 'Munteanu Radu', 'Prof. Dr.', 'Jurnalism');
INSERT INTO profesor VALUES (26, 'Popescu Gabriela', 'Conf. Dr.', 'Științe Politice');
INSERT INTO profesor VALUES (27, 'Cristescu Ion', 'Prof. Dr.', 'Electronică și Telecomunicații');
INSERT INTO profesor VALUES (28, 'Iancu Sorin', 'Lector Dr.', 'Matematică');
INSERT INTO profesor VALUES (29, 'Dumitrache Carmen', 'Prof. Dr.', 'Tehnologia Informației');
INSERT INTO profesor VALUES (30, 'Nicolae Elena', 'Conf. Dr.', 'Studii Internaționale');
